### ISSUE TITLE
problem with french locales

### ISSUE THREAD

**Issue by gerbier** [lynix/journalcheck#2]
I am french, so my locale is LANG=fr_FR.UTF-8
and the date in journalctl output is like :
oct. 12 15:59:10 EliteBook-ubuntu dbus-daemon[2761]: [session uid=1000 pid=2761] Successfully activated service 'ca.desrt.dconf'

and this do not match the begin of filters
^\w{3} [ :[:digit:]]{11} [._[:alnum:]-]+

So I suggest to add in journalcheck.sh code a line to force the locale to POSIX as the following patch
diff --git a/journalcheck.sh b/journalcheck.sh
index a45467d..abde11e 100755
--- a/journalcheck.sh
+++ b/journalcheck.sh
@@ -5,6 +5,7 @@
 
 #  This software is released under the terms of the MIT License, see LICENSE.
 
+export LANG=POSIX
 
 FILTERS_GLOBAL=${JC_FILTERS_GLOBAL:-"/usr/lib/journalcheck"}
 FILTERS_LOCAL=${JC_FILTERS_USER:-~/".journalcheck.d"}

**Comment by lynix** [comment]
Merci pour votre proposition, c'est vraiment une correction!

Would you like to submit a pull request or shall I apply your patch from this comment?

**Comment by gerbier** [comment]
Sorry to be so late : I have submit a patch request

**Comment by lynix** [comment]
Thanks, merged! :)
